name = 'flameshot'
from = 'base'

version = '13.3.0'

devDependencies = ['wget', 'apteryx']

build = """
wget -O flameshot.deb \
  https://github.com/flameshot-org/flameshot/releases/download/v{{VERSION}}/flameshot-{{VERSION}}-1.ubuntu-22.04.amd64.deb
apteryx ./flameshot.deb
rm flameshot.deb
"""

exports = [
  "/etc/ts.conf",
  "/etc/vulkan/",
  "/usr/bin/flameshot",
  "/usr/lib/x86_64-linux-gnu/dri/",
  "/usr/lib/x86_64-linux-gnu/gbm/",
  "/usr/lib/x86_64-linux-gnu/libb2.so.1",
  "/usr/lib/x86_64-linux-gnu/libb2.so.1.0.4",
  "/usr/lib/x86_64-linux-gnu/libdouble-conversion.so.3",
  "/usr/lib/x86_64-linux-gnu/libdouble-conversion.so.3.1",
  "/usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1",
  "/usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0",
  "/usr/lib/x86_64-linux-gnu/libdrm_intel.so.1",
  "/usr/lib/x86_64-linux-gnu/libdrm_intel.so.1.0.0",
  "/usr/lib/x86_64-linux-gnu/libdrm.so.2",
  "/usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0",
  "/usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0",
  "/usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libEGL.so.1",
  "/usr/lib/x86_64-linux-gnu/libEGL.so.1.1.0",
  "/usr/lib/x86_64-linux-gnu/libevdev.so.2",
  "/usr/lib/x86_64-linux-gnu/libevdev.so.2.3.0",
  "/usr/lib/x86_64-linux-gnu/libfontconfig.so.1",
  "/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.12.1",
  "/usr/lib/x86_64-linux-gnu/libfreetype.so.6",
  "/usr/lib/x86_64-linux-gnu/libfreetype.so.6.20.1",
  "/usr/lib/x86_64-linux-gnu/libgallium-25.0.7-0ubuntu0.24.04.2.so",
  "/usr/lib/x86_64-linux-gnu/libgbm.so.1",
  "/usr/lib/x86_64-linux-gnu/libgbm.so.1.0.0",
  "/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0",
  "/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libGLX_indirect.so.0",
  "/usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0",
  "/usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libGLX.so.0",
  "/usr/lib/x86_64-linux-gnu/libGLX.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libgomp.so.1",
  "/usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0",
  "/usr/lib/x86_64-linux-gnu/libgraphite2.so.2.0.0",
  "/usr/lib/x86_64-linux-gnu/libgraphite2.so.3",
  "/usr/lib/x86_64-linux-gnu/libgraphite2.so.3.2.1",
  "/usr/lib/x86_64-linux-gnu/libgudev-1.0.so.0",
  "/usr/lib/x86_64-linux-gnu/libgudev-1.0.so.0.3.0",
  "/usr/lib/x86_64-linux-gnu/libharfbuzz.so.0",
  "/usr/lib/x86_64-linux-gnu/libharfbuzz.so.0.60830.0",
  "/usr/lib/x86_64-linux-gnu/libICE.so.6",
  "/usr/lib/x86_64-linux-gnu/libICE.so.6.3.0",
  "/usr/lib/x86_64-linux-gnu/libinput.so.10",
  "/usr/lib/x86_64-linux-gnu/libinput.so.10.13.0",
  "/usr/lib/x86_64-linux-gnu/libjpeg.so.8",
  "/usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2",
  "/usr/lib/x86_64-linux-gnu/libLLVM-20.so",
  "/usr/lib/x86_64-linux-gnu/libLLVM.so.20.1",
  "/usr/lib/x86_64-linux-gnu/libmd4c.so.0",
  "/usr/lib/x86_64-linux-gnu/libmd4c.so.0.4.8",
  "/usr/lib/x86_64-linux-gnu/libmtdev.so.1",
  "/usr/lib/x86_64-linux-gnu/libmtdev.so.1.0.0",
  "/usr/lib/x86_64-linux-gnu/libOpenGL.so.0",
  "/usr/lib/x86_64-linux-gnu/libOpenGL.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libpciaccess.so.0",
  "/usr/lib/x86_64-linux-gnu/libpciaccess.so.0.11.1",
  "/usr/lib/x86_64-linux-gnu/libpcre2-16.so.0",
  "/usr/lib/x86_64-linux-gnu/libpcre2-16.so.0.11.2",
  "/usr/lib/x86_64-linux-gnu/libpng16.so.16",
  "/usr/lib/x86_64-linux-gnu/libpng16.so.16.43.0",
  "/usr/lib/x86_64-linux-gnu/libproxy.so.0.5.4",
  "/usr/lib/x86_64-linux-gnu/libproxy.so.1",
  "/usr/lib/x86_64-linux-gnu/libproxy/",
  "/usr/lib/x86_64-linux-gnu/libQt6Core.so.6",
  "/usr/lib/x86_64-linux-gnu/libQt6Core.so.6.4.2",
  "/usr/lib/x86_64-linux-gnu/libQt6DBus.so.6",
  "/usr/lib/x86_64-linux-gnu/libQt6DBus.so.6.4.2",
  "/usr/lib/x86_64-linux-gnu/libQt6Gui.so.6",
  "/usr/lib/x86_64-linux-gnu/libQt6Gui.so.6.4.2",
  "/usr/lib/x86_64-linux-gnu/libQt6Network.so.6",
  "/usr/lib/x86_64-linux-gnu/libQt6Network.so.6.4.2",
  "/usr/lib/x86_64-linux-gnu/libQt6Svg.so.6",
  "/usr/lib/x86_64-linux-gnu/libQt6Svg.so.6.4.2",
  "/usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6",
  "/usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6.4.2",
  "/usr/lib/x86_64-linux-gnu/libQt6XcbQpa.so.6",
  "/usr/lib/x86_64-linux-gnu/libQt6XcbQpa.so.6.4.2",
  "/usr/lib/x86_64-linux-gnu/libsensors.so.5",
  "/usr/lib/x86_64-linux-gnu/libsensors.so.5.0.0",
  "/usr/lib/x86_64-linux-gnu/libSM.so.6",
  "/usr/lib/x86_64-linux-gnu/libSM.so.6.0.1",
  "/usr/lib/x86_64-linux-gnu/libts.so.0",
  "/usr/lib/x86_64-linux-gnu/libts.so.0.10.4",
  "/usr/lib/x86_64-linux-gnu/libvulkan.so.1",
  "/usr/lib/x86_64-linux-gnu/libvulkan.so.1.3.275",
  "/usr/lib/x86_64-linux-gnu/libwacom.so.9",
  "/usr/lib/x86_64-linux-gnu/libwacom.so.9.0.0",
  "/usr/lib/x86_64-linux-gnu/libwayland-client.so.0",
  "/usr/lib/x86_64-linux-gnu/libwayland-client.so.0.22.0",
  "/usr/lib/x86_64-linux-gnu/libwayland-server.so.0",
  "/usr/lib/x86_64-linux-gnu/libwayland-server.so.0.22.0",
  "/usr/lib/x86_64-linux-gnu/libX11-xcb.so.1",
  "/usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0",
  "/usr/lib/x86_64-linux-gnu/libX11.so.6",
  "/usr/lib/x86_64-linux-gnu/libX11.so.6.4.0",
  "/usr/lib/x86_64-linux-gnu/libXau.so.6",
  "/usr/lib/x86_64-linux-gnu/libXau.so.6.0.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.1.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-glx.so.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4",
  "/usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4.0.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-image.so.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-image.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1",
  "/usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1.0.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-present.so.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-randr.so.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-randr.so.0.1.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-render.so.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-render.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-shape.so.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-shape.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-shm.so.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-sync.so.1",
  "/usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-util.so.1",
  "/usr/lib/x86_64-linux-gnu/libxcb-util.so.1.0.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1",
  "/usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1.0.0",
  "/usr/lib/x86_64-linux-gnu/libxcb.so.1",
  "/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0",
  "/usr/lib/x86_64-linux-gnu/libXdmcp.so.6",
  "/usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0",
  "/usr/lib/x86_64-linux-gnu/libXext.so.6",
  "/usr/lib/x86_64-linux-gnu/libXext.so.6.4.0",
  "/usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0",
  "/usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libxkbcommon.so.0",
  "/usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0",
  "/usr/lib/x86_64-linux-gnu/libxshmfence.so.1",
  "/usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0",
  "/usr/lib/x86_64-linux-gnu/libXxf86vm.so.1",
  "/usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0",
  "/usr/lib/x86_64-linux-gnu/qt6/",
  "/usr/lib/x86_64-linux-gnu/ts0/",
  "/usr/local/share/fonts",
  "/usr/share/applications/org.flameshot.Flameshot.desktop",
  "/usr/share/apport/package-hooks/source_fontconfig.py",
  "/usr/share/apport/package-hooks/source_mtdev.py",
  "/usr/share/bash-completion/completions/flameshot",
  "/usr/share/dbus-1/interfaces/org.flameshot.Flameshot.xml",
  "/usr/share/dbus-1/services/org.flameshot.Flameshot.service",
  "/usr/share/doc-base/libpng16-16t64.libpng16",
  "/usr/share/flameshot/",
  "/usr/share/fontconfig/",
  "/usr/share/gettext/",
  "/usr/share/metainfo/org.flameshot.Flameshot.metainfo.xml",
]

[diff]
exclude = [
  "/etc/X11/**",
  "/etc/fonts/",
  "/etc/glvnd/",
  "/etc/init.d/x11-common",
  "/etc/ld.so.cache",
  "/etc/rcS.d/S01x11-common",
  "/etc/sensors.d/",
  "/etc/sensors3.conf",
  "/root/.wget-hsts",
  "/usr/bin/X11",
  "/usr/bin/fc-*",
  "/usr/bin/update-mime-database",
  "/usr/include/X11",
  "/usr/lib/X11",
  "/usr/lib/udev/hwdb.d/",
  "/usr/lib/udev/libinput-device-group",
  "/usr/lib/udev/libinput-fuzz-extract",
  "/usr/lib/udev/libinput-fuzz-to-zero",
  "/usr/lib/udev/rules.d/65-libwacom.rules",
  "/usr/lib/udev/rules.d/80-libinput-device-groups.rules",
  "/usr/lib/udev/rules.d/90-libinput-fuzz-override.rules",
  "/usr/share/X11/",
  "/usr/share/bug/*",
  "/usr/share/doc-base/fontconfig.fontconfig-user",
  "/usr/share/doc-base/libpng16-16.libpng16",
  "/usr/share/doc-base/shared-mime-info.shared-mime-info",
  "/usr/share/doc/*",
  "/usr/share/drirc.d/",
  "/usr/share/fish/",
  "/usr/share/fonts/",
  "/usr/share/gettext/its/shared-mime-info.its",
  "/usr/share/gettext/its/shared-mime-info.loc",
  "/usr/share/glvnd/",
  "/usr/share/icons/**",
  "/usr/share/libdrm/",
  "/usr/share/libinput/",
  "/usr/share/libwacom/",
  "/usr/share/lintian/**",
  "/usr/share/man/*",
  "/usr/share/metainfo/",
  "/usr/share/mime/",
  "/usr/share/pkgconfig/*",
  "/usr/share/xml/fontconfig/",
  "/usr/share/zsh/site-functions/",
  "/var/cache/**",
  "/var/lib/apt/*",
  "/var/lib/dpkg/**",
  "/var/lib/ucf/*",
  "/var/log/**",
  "/var/apt/lists/*",
]

[checkUpdates]
type = 'github-release'
url = 'https://github.com/flameshot-org/flameshot'
removePrefix = 'v'
