name = 'lazyjj'
from = 'base'

version = '0.6.1'

devDependencies = ['rust', 'cargo-binstall']

build = """
cargo binstall --no-track --disable-telemetry \
  --version='{{VERSION}}' lazyjj

rm /root/.cargo/binstall.toml
mv /root/.cargo/bin/lazyjj /usr/local/bin/lazyjj
"""

exports = ['/usr/local/bin/lazyjj']

[checkUpdates]
type = 'github-release'
url = 'https://github.com/Cretezy/lazyjj'
matchPrerelease = false
removePrefix = 'v'
